"""
pyrulearn.rule
=================

Core rule representation: `Rule`, a conjunction of Boolean literals --
**pure logic**, no weight and no free-form metadata.
`WeightedRule` is the subclass that adds one declarative scalar `weight`
(a ProbLog probability, a committed per-rule confidence). Collections of
rules that make predictions together (`RuleModel` and its family --
`SingleRule`, `OneClassRuleSet`, `FlatRuleSet`, `DecisionList`, ...) live
in `pyrulearn.models`, built on top of `Rule`.

`Rule` design
--------------
A rule is a conjunction of literals, each requiring one feature to be
True (`Literal(feature)`). Negation is a *separate feature* -- e.g.
``color!=red`` or ``not smoker``, generated by `DataSpecBuilder` when an
attribute is declared with negation and paired via
`DataSpec.negation_of` -- not a flag on the literal. Internally a rule
is one integer bitmask (`_mask`) so a single example's coverage is an
O(1)-ish subset check:

    covers = (x_bits & mask) == mask

and whole-dataset coverage (`covers_data_packed`) is the same check
vectorized over a `numpy.packbits`-packed copy of the data (see
`pyrulearn.data.BooleanDataRepresentation`), instead of
per-feature Python loops.

Beyond that bitmask core, `Rule` adds:
- **optional ordering** of conditions -- a rule can carry the order its
  conditions were added/tested in (e.g. reflecting how a sequential-
  covering learner grew it), or treat that order as insignificant and
  always display/compare canonically. Coverage itself is always
  order-independent (a conjunction is a conjunction); order only affects
  presentation and provenance. This is unrelated to `RuleList`'s
  rule-level ordering in `pyrulearn.models` -- that's the order of
  whole rules in a decision list, not conditions within one rule.
- a reference to a **DataSpec** (see `pyrulearn.data.spec`) instead of
  loose `feature_names`/`n_features` arguments -- the rule's feature
  space and (optionally) the data it was learned from / is scored against
  live in one place, shared across rules.
- **multiple output formats** via `to_string(fmt=...)`: a logic notation,
  a Prolog-style clause, a positional pattern string, or a bare
  comma-separated condition list. `fmt` is optional -- omitted, it falls
  back to a rule's own `default_fmt` if set, else the class-wide
  `Rule.DEFAULT_FORMAT` (``"prolog"``); `__repr__` goes through the same
  resolution, so a rule's configured format is also what you see printed.
- **constraint-aware consistency checks** (`is_consistent`,
  `implied_conditions`) when the `DataSpec` carries typed attributes (see
  `pyrulearn.attributes`) -- e.g. whether a rule is self-contradictory
  (`color=red` and `color=blue`), or what it implies beyond its explicit
  conditions.

This module is independent of scikit-learn and SAT solvers -- those
integrations live in separate modules so this file has no hard
dependencies beyond numpy.
"""

from __future__ import annotations

import math
import re
from typing import Any, FrozenSet, List, NamedTuple, Optional, Sequence, Tuple, Union

import numpy as np

from .attributes import FeatureValues
from .data import DataSpec
from .data import BooleanDataRepresentation, DataRepresentation


class Literal(NamedTuple):
    """A single rule condition: feature `feature` must be True. Negating
    a test means conditioning on a *different* feature (its negation --
    ``color!=red`` for ``color=red``, ``age<30`` for ``age>=30``, ``not
    smoker`` for ``smoker``) -- see `DataSpec.negation_of` -- so there's
    no polarity flag here."""
    feature: int


ConditionLike = Union[Literal, int, Tuple[int]]


class Rule:
    """A conjunction of Boolean literals, optionally ordered, optionally
    tied to a `DataSpec`.

    Parameters
    ----------
    conditions : sequence of Literal or (feature_index, value) pairs
        The rule's conditions. Order is preserved as given; whether that
        order is *meaningful* is controlled by `ordered`. Duplicate
        conditions on the same feature (with the same value) are
        silently collapsed to their first occurrence; conflicting
        conditions on the same feature (True and False both required)
        raise `ValueError`.
    target : Any, optional
        The class this rule predicts. `None` for class-agnostic rules.
    dataspec : DataSpec, optional
        The feature-space (and optionally data) this rule is defined
        over. Used to resolve feature names for display, and as the
        default target for coverage checks over data.
    ordered : bool, default False
        If True, `conditions` order is treated as significant (kept
        as-is in output). If False (default), output uses a canonical
        ascending-feature-index order regardless of construction order;
        the order actually supplied is still stored (via `conditions`)
        and can be recovered or switched to later with `reorder`.
    n_features : int, optional
        Size of the feature space the bitmask is over. Defaults to
        `dataspec.n_features` if a dataspec is given, else inferred from
        the largest feature index used (which may under-count trailing
        unused features -- prefer passing a dataspec or n_features
        explicitly when this matters, e.g. for the "pattern" output
        format or for combining rules from a shared space).
    default_fmt : str, optional
        This rule's own default `to_string`/`__repr__` format (see
        `to_string` for the choices), used whenever `to_string` is called
        without an explicit `fmt=`. Falls back to `Rule.DEFAULT_FORMAT`
        (class-wide, ``"prolog"``) if not set. An explicit `fmt=` passed
        to `to_string` always wins over both.
    """

    #: Class-wide fallback for `to_string`'s `fmt` when neither an
    #: explicit `fmt=` argument nor a rule's own `default_fmt` is given.
    DEFAULT_FORMAT: str = "prolog"

    def __init__(
        self,
        conditions: Sequence[ConditionLike] = (),
        target: Any = None,
        dataspec: Optional[DataSpec] = None,
        ordered: bool = False,
        n_features: Optional[int] = None,
        default_fmt: Optional[str] = None,
    ):
        self.target = target
        self.dataspec = dataspec
        self.ordered = ordered
        self.default_fmt = default_fmt

        seen: set = set()
        normalized: List[Literal] = []
        for c in conditions:
            if isinstance(c, Literal):
                feat = int(c.feature)
            elif isinstance(c, (tuple, list)):
                feat = int(c[0])
            else:
                feat = int(c)
            if feat in seen:
                continue  # exact duplicate; drop, keep first occurrence's position
            seen.add(feat)
            normalized.append(Literal(feat))
        self.conditions: Tuple[Literal, ...] = tuple(normalized)

        if n_features is not None:
            self.n_features = n_features
        elif dataspec is not None:
            self.n_features = dataspec.n_features
        else:
            self.n_features = (max((l.feature for l in self.conditions), default=-1) + 1)

        self._mask = 0
        for lit in self.conditions:
            self._mask |= (1 << lit.feature)

    # -- construction helpers --------------------------------------------

    @classmethod
    def from_pos_neg(
        cls,
        pos: Sequence[int] = (),
        neg: Sequence[int] = (),
        target: Any = None,
        dataspec: Optional[DataSpec] = None,
        n_features: Optional[int] = None,
        default_fmt: Optional[str] = None,
    ) -> "Rule":
        """Convenience constructor for the common unordered case.
        `pos` are feature indices required True. `neg` are feature
        indices whose *negation* is required -- each is translated to its
        negation feature via `dataspec.negation_of(i)` (so a `dataspec`
        is required when `neg` is non-empty, and every `neg` index must
        have a negation feature). Conditions end up as positive literals
        on `pos` then the translated `neg`, ascending, `ordered=False`."""
        features = sorted(set(pos))
        for i in sorted(set(neg)):
            if dataspec is None:
                raise ValueError("Rule.from_pos_neg with neg= needs a dataspec to resolve negation features")
            ni = dataspec.negation_of(i)
            if ni is None:
                raise ValueError(
                    f"feature {i} ({dataspec.feature_name(i)}) has no negation feature in this DataSpec "
                    "-- build it with negation on, or condition on the negation feature directly"
                )
            features.append(ni)
        return cls([Literal(f) for f in features], target=target, dataspec=dataspec, ordered=False,
                   n_features=n_features, default_fmt=default_fmt)

    @classmethod
    def from_example(
        cls,
        x: Sequence[Union[int, bool, float]],
        target: Any = None,
        dataspec: Optional[DataSpec] = None,
        feature_indices: Optional[Sequence[int]] = None,
        ordered: bool = False,
        default_fmt: Optional[str] = None,
    ) -> "Rule":
        """Most specific rule covering exactly one example (all literals
        fixed). `x` may contain NaN for "don't care" positions (skipped).
        """
        idxs = feature_indices if feature_indices is not None else range(len(x))
        conditions = []
        for i, v in zip(idxs, x):
            if v is None or (isinstance(v, float) and math.isnan(v)):
                continue
            if v:
                conditions.append(Literal(i))
            elif dataspec is not None and dataspec.negation_of(i) is not None:
                conditions.append(Literal(dataspec.negation_of(i)))
            # else: a 0 feature with no negation feature -- can't be pinned, skip
        return cls(conditions, target=target, dataspec=dataspec, ordered=ordered,
                   n_features=len(x), default_fmt=default_fmt)

    @classmethod
    def from_pattern_string(
        cls,
        pattern: str,
        target: Any = None,
        dataspec: Optional[DataSpec] = None,
        n_features: Optional[int] = None,
        ordered: bool = False,
        default_fmt: Optional[str] = None,
    ) -> "Rule":
        """Parse a positional pattern like ``"1 0 0 1 0"``: ``1`` at
        position i means feature i is a condition of the rule, ``0``
        means it isn't (``-``/``?`` accepted as aliases for ``0``).
        Whitespace- or comma-separated tokens. (Since negation is now a
        separate feature, there's no ``0``-means-"required-False" case
        any more -- a ``0`` is simply "not in the rule".)"""
        tokens = pattern.replace(",", " ").split()
        conditions = []
        for i, tok in enumerate(tokens):
            t = tok.strip().lower()
            if t in ("1", "true", "t"):
                conditions.append(Literal(i))
            elif t in ("0", "-", "?", "nan", "x", "false", "f"):
                continue
            else:
                raise ValueError(f"Unrecognized token {tok!r} in pattern string")
        return cls(conditions, target=target, dataspec=dataspec, ordered=ordered,
                   n_features=n_features or len(tokens), default_fmt=default_fmt)

    # -- derived views of the condition set ------------------------------

    @property
    def pos(self) -> Tuple[int, ...]:
        """This rule's condition feature indices, canonically sorted.
        (Every literal is positive now; kept as `pos` for the many
        callers that used it that way.)"""
        return tuple(sorted(l.feature for l in self.conditions))

    features = pos

    def canonical_conditions(self) -> Tuple[Literal, ...]:
        """Conditions sorted by ascending feature index, regardless of
        `self.ordered` or construction order."""
        return tuple(sorted(self.conditions, key=lambda l: l.feature))

    def _display_conditions(self) -> Tuple[Literal, ...]:
        return self.conditions if self.ordered else self.canonical_conditions()

    def _rebuilt(
        self,
        conditions: Sequence[ConditionLike],
        *,
        dataspec: Optional[DataSpec],
        ordered: bool,
        n_features: Optional[int] = None,
    ) -> "Rule":
        """A copy of this rule with a new condition set / dataspec /
        order, carrying over `target`, `default_fmt` -- and, in
        subclasses, any extra declarative fields (`WeightedRule.weight`).
        The single place `reorder`/`remap` build their result, so a
        subclass overrides this one method rather than each of them."""
        return type(self)(
            conditions, target=self.target, dataspec=dataspec, ordered=ordered,
            n_features=n_features, default_fmt=self.default_fmt,
        )

    def reorder(self, feature_order: Sequence[int]) -> "Rule":
        """Return a copy with conditions reordered to `feature_order` (a
        permutation of this rule's condition feature indices), with
        `ordered` set to True on the result."""
        by_feature = {l.feature: l for l in self.conditions}
        if set(feature_order) != set(by_feature):
            raise ValueError("feature_order must be a permutation of this rule's condition features")
        new_conditions = [by_feature[f] for f in feature_order]
        return self._rebuilt(new_conditions, dataspec=self.dataspec, ordered=True,
                             n_features=self.n_features)

    def remap(self, new_dataspec: DataSpec) -> "Rule":
        """Rebuild this rule's conditions against a different, compatible
        `DataSpec`, translating each condition's feature index **by
        name**: for every `Literal(old_idx)`,
        `self.dataspec.feature_name(old_idx)` must exist as a feature
        name in `new_dataspec` (via `new_dataspec.feature_index`).

        A pure structural translation -- no data is touched, nothing is
        recomputed -- what lets several independently-imported models
        (each built against its own per-model `DataSpec`) be rebased
        onto one shared `DataSpec` (e.g. built via
        `pyrulearn.data.merge_dataspecs`) before scoring them
        together against one shared dataset, without ever needing more
        than one model's worth of Boolean data in memory at a time.

        Raises `ValueError` if this rule has no `dataspec` (nothing to
        resolve feature names from), or if any condition's feature name
        has no match in `new_dataspec` -- never silently drops a
        condition. Any measured `stats()` a `SingleRule` wrapper carries
        is NOT carried over -- it was computed against the *old*
        DataSpec's rows and is stale after a remap; re-annotate against
        `new_dataspec`'s data for fresh stats.
        """
        if self.dataspec is None:
            raise ValueError("remap() needs self.dataspec to resolve condition feature names from")
        new_conditions = []
        for lit in self.conditions:
            name = self.dataspec.feature_name(lit.feature)
            try:
                new_idx = new_dataspec.feature_index(name)
            except KeyError:
                raise ValueError(
                    f"Cannot remap rule: feature {name!r} (index {lit.feature} in the source "
                    "DataSpec) has no matching feature in the target DataSpec"
                ) from None
            new_conditions.append(Literal(new_idx))
        return self._rebuilt(new_conditions, dataspec=new_dataspec, ordered=self.ordered)

    def order_by_precision(self, data: BooleanDataRepresentation, positive_class: Any = None) -> "Rule":
        """Return a copy with conditions greedily reordered by incremental
        precision on `data`: at each step, among the
        not-yet-placed conditions, pick whichever one -- when added to
        the conditions already placed -- yields the highest precision
        (fraction of covered examples in `positive_class`) against the
        data, breaking ties toward higher coverage. `positive_class`
        defaults to `self.target`.

        This is the standard greedy literal-ordering heuristic from
        sequential-covering rule construction (FOIL/CN2-style), applied
        after the fact as a way to compute a reasonable default order for
        an otherwise-unordered rule. See `reorder` to specify an order
        directly instead.
        """
        if data.y is None:
            raise ValueError("order_by_precision needs data.y")
        pos_class = positive_class if positive_class is not None else self.target
        if pos_class is None:
            raise ValueError("order_by_precision needs positive_class (or a Rule with a target)")
        pos_mask = data.y == pos_class
        spec = data.spec

        remaining = list(self.conditions)
        chosen: List[Literal] = []

        def precision(lit: Literal):
            trial = Rule(chosen + [lit], dataspec=spec, n_features=spec.n_features)
            cov = trial.covers_data_packed(data)
            n = int(cov.sum())
            if n == 0:
                return (-1.0, 0)  # covers nothing: worst possible, sorts last
            return (int(np.sum(cov & pos_mask)) / n, n)

        while remaining:
            best = max(remaining, key=precision)
            chosen.append(best)
            remaining.remove(best)
        return self.reorder([lit.feature for lit in chosen])

    # -- coverage ---------------------------------------------------------

    def covers_bits(self, x_bits: int) -> bool:
        """O(1)-ish subset check for a single example given as an int
        bitmask (bit i set iff feature i is True)."""
        return (x_bits & self._mask) == self._mask

    def covers(self, x: Sequence[Union[int, bool]]) -> bool:
        """Coverage check for a single example given as a 0/1/bool sequence."""
        bits = 0
        for i, v in enumerate(x):
            if v:
                bits |= (1 << i)
        return self.covers_bits(bits)

    def covers_data(self, data: "DataRepresentation") -> np.ndarray:
        """Vectorized coverage over `data`. Returns a boolean array of
        shape (n_samples,). Delegates to `data.coverage(self)` -- each
        `DataRepresentation` subclass computes it however its own
        encoding does best."""
        return data.coverage(self)

    def covers_data_packed(self, data: "DataRepresentation") -> np.ndarray:
        """Backwards-compatible alias for `covers_data`. Coverage now
        dispatches on the `DataRepresentation` subclass
        (`BooleanDataRepresentation` uses its `numpy.packbits` cache), so
        there's a single code path regardless of which name the caller
        uses."""
        return data.coverage(self)

    # -- generalization / relations ---------------------------------------

    def generalize(self, other: "Rule") -> "Rule":
        """Least general generalization (LGG): keep only shared literals,
        in `self`'s condition order."""
        other_feats = {l.feature for l in other.conditions}
        shared = [l for l in self.conditions if l.feature in other_feats]
        return Rule(
            shared,
            target=self.target if self.target == other.target else None,
            dataspec=self.dataspec or other.dataspec,
            n_features=max(self.n_features, other.n_features),
            default_fmt=self.default_fmt or other.default_fmt,
        )

    def is_more_specific(self, other: "Rule", include_target: bool = False) -> bool:
        """True if `self` is at least as specific as `other` (implies it) --
        i.e. `self`'s conditions are a superset of `other`'s. Ignores
        target by default; pass `include_target=True` to also require
        `self.target == other.target` -- what `<=`/`>=`/`<`/`>` use, to stay
        consistent with `==` (which always checks target): required for
        antisymmetry (`a <= b and b <= a` must imply `a == b`), not just
        a style choice."""
        if include_target and self.target != other.target:
            return False
        return (self._mask & other._mask) == other._mask

    def is_more_general(self, other: "Rule", include_target: bool = False) -> bool:
        """True if `self` is at least as general as `other` (is implied by
        it) -- i.e. `self`'s conditions are a subset of `other`'s. Mirrors
        `is_more_specific`; see it for `include_target`."""
        return other.is_more_specific(self, include_target=include_target)

    def length(self) -> int:
        """Number of literals (rule "size")."""
        return len(self.conditions)

    # -- constraint-aware consistency (needs a DataSpec with attributes) ---

    def is_consistent(self, dataspec: Optional[DataSpec] = None) -> bool:
        """Check this rule's conditions against `dataspec`'s constraints
        (or `self.dataspec`'s). True if attribute-less, or if no
        constraints are violated -- e.g. False for a rule requiring both
        ``color=red`` and ``color=blue``."""
        dv = dataspec or self.dataspec
        if dv is None or not dv.constraints:
            return True
        fixed: FeatureValues = {l.feature: True for l in self.conditions}
        try:
            dv.propagate(fixed)
            return True
        except ValueError:
            return False

    def implied_conditions(self, dataspec: Optional[DataSpec] = None) -> Tuple[Literal, ...]:
        """Positive conditions this rule logically implies via
        `dataspec`'s constraints but doesn't state explicitly -- e.g. a
        rule with ``age>=30`` implies ``age>=20`` (lower threshold), and
        a rule with ``color=red`` implies ``color!=green`` and
        ``color!=blue``. Returns an empty tuple for attribute-less
        DataSpecs. Raises ValueError if the rule's own conditions are
        already inconsistent -- check `is_consistent` first if that's a
        possibility."""
        dv = dataspec or self.dataspec
        if dv is None or not dv.constraints:
            return ()
        fixed: FeatureValues = {l.feature: True for l in self.conditions}
        closure = dv.propagate(fixed)
        extra = [Literal(i) for i, v in closure.items() if v is True and i not in fixed]
        return tuple(sorted(extra, key=lambda l: l.feature))

    def specialize(
        self, dataspec: Optional[DataSpec] = None, mask: Optional[FrozenSet[int]] = None
    ) -> List[Tuple["Rule", FrozenSet[int]]]:
        """All one-literal specializations of `self` (one per feature
        still open in `mask` -- every literal is positive now).
        `dataspec` (falling back to `self.dataspec`) supplies the
        constraints used to prune redundant/contradictory refinements
        and to close out sibling features an added literal determines
        -- with neither available, every not-yet-used feature stays a
        candidate, no pruning.

        `mask` defaults to every feature not already in `self.conditions`
        -- always re-derivable this way from
        `dataspec.propagate(self.conditions)` alone, so omitting it for a
        one-off call is fine. Search strategies should still thread the
        returned mask through explicitly across refinement steps rather
        than recomputing via `propagate` from scratch at every node:
        equivalent result, but threading avoids redoing that computation
        repeatedly as the search grows -- an efficiency win, not a
        correctness requirement.

        Returns `(child_rule, child_mask)` pairs, one per open feature
        that doesn't contradict `self`'s existing conditions.
        """
        dv = dataspec or self.dataspec
        used = {lit.feature for lit in self.conditions}
        if mask is None:
            mask = frozenset(range(self.n_features)) - used

        results: List[Tuple["Rule", FrozenSet[int]]] = []
        for i in sorted(mask):  # deterministic order -- frozenset iteration isn't
            new_conditions = self.conditions + (Literal(i),)
            if dv is not None and dv.constraints:
                fixed: FeatureValues = {l.feature: True for l in new_conditions}
                try:
                    closure = dv.propagate(fixed)
                except ValueError:
                    continue  # contradicts dv's constraints
                determined = set(closure)  # every feature this refinement pins, either way
            else:
                determined = {i}
            child = Rule(
                new_conditions, target=self.target, dataspec=dv,
                n_features=self.n_features, default_fmt=self.default_fmt,
            )
            results.append((child, mask - determined))
        return results

    # -- output formats -----------------------------------------------------

    def _feature_name(self, i: int) -> str:
        if self.dataspec is not None:
            return self.dataspec.feature_name(i)
        return f"f{i}"

    def _feature_spec(self, i: int):
        if self.dataspec is not None and i < len(self.dataspec.feature_specs):
            return self.dataspec.feature_specs[i]
        return None

    def _literal_str(self, lit: Literal, ascii: bool = False) -> str:
        """Render one (positive) literal, using the DataSpec's
        FeatureSpec (if any) for attribute-aware phrasing: ``color =
        red`` / ``color != red``, ``age >= 30`` / ``age < 30`` / ``age
        <= 30``, ``red in tags``, ``not smoker`` for a negated Boolean,
        or the relational feature's `expression` -- falling back to the
        plain feature name for attribute-less features."""
        spec = self._feature_spec(lit.feature)
        if spec is not None:
            if spec.op == "==":
                return f"{spec.attribute} = {spec.value}"
            if spec.op == "!=":
                return f"{spec.attribute} {'!=' if ascii else '≠'} {spec.value}"
            if spec.op in (">=", ">", "<", "<="):
                return f"{spec.attribute} {spec.op} {spec.value}"
            if spec.op == "has":
                return f"{spec.value} {'in' if ascii else '∈'} {spec.attribute}"
            if spec.op == "not":
                return f"{'NOT ' if ascii else '¬'}{spec.attribute}"
            if spec.op == "expr":
                return spec.expression or spec.name
        return self._feature_name(lit.feature)

    _PROLOG_BARE_ATOM = re.compile(r"^[a-z][a-zA-Z0-9_]*$")

    def _prolog_atom(self, s: str) -> str:
        """Quote `s` as a Prolog atom if it isn't already a valid bare
        one (must start with a lowercase letter) -- e.g. a target class
        that's literally the string ``"1"`` would otherwise render as
        the syntactically invalid ``1(X) :- ...`` head; this renders
        ``'1'(X) :- ...`` instead. A class/feature name that's already a
        meaningful lowercase word (the usual case) is left untouched."""
        return s if self._PROLOG_BARE_ATOM.match(s) else f"'{s}'"

    def _prolog_literal(self, lit: Literal) -> str:
        """Render one (positive) literal in Prolog style: functional
        attribute/value form for nominal/set features (``color(X,
        red)``), an explicit inequality for ``!=`` (``color(X, V), V \\=
        red``), threshold form for numeric (``age(X, V), V >= 30``),
        ``\\+smoker(X)`` for a negated Boolean, a named predicate for
        relational features, a plain 0-ary atom otherwise."""
        spec = self._feature_spec(lit.feature)
        if spec is not None:
            if spec.op in ("==", "has"):
                return f"{spec.attribute}(X, {spec.value})"
            if spec.op == "!=":
                return f"{spec.attribute}(X, V), V \\= {spec.value}"
            if spec.op in (">=", ">", "<", "<="):
                return f"{spec.attribute}(X, V), V {spec.op} {spec.value}"
            if spec.op == "not":
                return f"\\+{spec.attribute}(X)"
            if spec.op == "expr":
                return f"{spec.name.replace(' ', '_')}(X)"
        return f"{self._feature_name(lit.feature)}(X)"

    def logic_body(self, ascii: bool = False) -> str:
        """The "logic" format's conjunction, without the ``→ target``
        head -- e.g. ``"age_gt_30 ∧ smoker"``, or ``"TRUE"`` for an
        empty condition set. Used by `to_string(fmt="logic")` itself,
        and reused by `pyrulearn.models.RuleSet.to_string`/`RuleList.
        to_string` to build multi-rule DNF blocks (one disjunct per rule)
        when printing a whole model.
        """
        and_sym = " AND " if ascii else " ∧ "
        lits = [self._literal_str(l, ascii=ascii) for l in self._display_conditions()]
        return and_sym.join(lits) if lits else "TRUE"

    def to_string(self, fmt: Optional[str] = None, ascii: bool = False) -> str:
        """Render this rule in one of several formats.

        fmt
        ----
        "logic"      f0 ∧ f3 ∧ not_f1 → target   (unicode ∧/→, or
                     "AND"/"->" if ``ascii=True``)
        "prolog"     target(X) :- f0(X), f3(X), \\+f1(X).
                     (head predicate is "rule" if target is None)
        "pattern"    "1 0 0 1 0"  positional 1/0 string (1 = feature is
                     a condition); needs `self.n_features` (set via
                     `dataspec=` or `n_features=`)
        "conditions" "f0, f3, not f1"  bare literal list, no connective/head

        If `fmt` is omitted, uses this rule's own `default_fmt` if set,
        else `Rule.DEFAULT_FORMAT` (``"prolog"``).

        Condition order follows `self.ordered`: if True, the order the
        rule was constructed with is used; if False (default), a
        canonical ascending-feature-index order is used instead.
        """
        if fmt is None:
            fmt = self.default_fmt if self.default_fmt is not None else Rule.DEFAULT_FORMAT
        conds = self._display_conditions()

        if fmt == "pattern":
            if self.n_features is None:
                raise ValueError("pattern format requires n_features (set via dataspec= or n_features=)")
            tokens = ["0"] * self.n_features
            for lit in conds:
                tokens[lit.feature] = "1"
            return " ".join(tokens)

        if fmt == "conditions":
            return ", ".join(self._literal_str(l, ascii=ascii) for l in conds)

        if fmt == "prolog":
            head_pred = self._prolog_atom(str(self.target)) if self.target is not None else "rule"
            body_lits = [self._prolog_literal(l) for l in conds]
            body = ", ".join(body_lits) if body_lits else "true"
            return f"{head_pred}(X) :- {body}."

        if fmt == "logic":
            arrow_sym = "->" if ascii else "→"
            head = f" {arrow_sym} {self.target}" if self.target is not None else ""
            return f"{self.logic_body(ascii=ascii)}{head}"

        raise ValueError(f"Unknown format {fmt!r}; choose from logic/prolog/pattern/conditions")

    # -- misc ---------------------------------------------------------------

    def __hash__(self):
        return hash((self.pos, self.target))

    def __eq__(self, other):
        # Equality is order-independent: two rules with the same
        # condition set and target are the same rule, regardless of
        # how/whether that order is tracked for display purposes.
        return isinstance(other, Rule) and self.pos == other.pos and self.target == other.target

    # Generality forms a *partial* order (two rules can be incomparable --
    # neither implies the other), not a total one, so every comparison is
    # implemented independently below rather than via functools.total_ordering
    # (which assumes totality and would answer incomparable pairs wrong) --
    # same reason frozenset (also a subset/partial order) doesn't use it
    # either. All four check target, to stay consistent with __eq__ above
    # (required for antisymmetry: a <= b and b <= a must imply a == b) --
    # use is_more_specific/is_more_general directly with include_target=False
    # for the target-agnostic version.

    def __le__(self, other):
        if not isinstance(other, Rule):
            return NotImplemented
        return self.is_more_specific(other, include_target=True)

    def __ge__(self, other):
        if not isinstance(other, Rule):
            return NotImplemented
        return self.is_more_general(other, include_target=True)

    def __lt__(self, other):
        if not isinstance(other, Rule):
            return NotImplemented
        return self <= other and self != other

    def __gt__(self, other):
        if not isinstance(other, Rule):
            return NotImplemented
        return self >= other and self != other

    def __repr__(self) -> str:
        return f"{type(self).__name__}({self.to_string()})"


def _fmt_weight(w: float) -> str:
    """Compact weight rendering: ``0.8``, ``1``, ``0.333`` -- no trailing
    zeros, no scientific notation for the usual [0, 1] range."""
    return f"{w:g}"


class WeightedRule(Rule):
    """A `Rule` with one extra, purely **declarative** field: a scalar
    `weight`. This is the home for a probability (ProbLog-style
    ``0.8::head :- body``), a learned per-rule confidence a model commits
    to, or any other number that is *part of the model* rather than
    measured against a dataset -- see `pyrulearn.models` for the
    weight-vs-stats split (weight: declarative, usable at predict time;
    stats: measured, annotation only).

    Everything else is `Rule`: `weight` takes no part in logical
    identity, so ``WeightedRule([0], target="a", weight=0.8) ==
    Rule([0], target="a")`` (two rules with the same body and head are
    the same rule, differently annotated) -- and `set`/`dict` de-dup by
    logic accordingly. Logical operations that produce a *new* rule from
    an old one's structure -- `generalize`, `specialize` -- return a
    plain `Rule`, since a refinement/generalization has no well-defined
    weight; `reorder`/`remap` (structure-preserving copies) keep it.

    `to_string` / `__repr__` prefix or annotate the base rendering with
    the weight: ``0.8::target(X) :- f0(X).`` for ``prolog``, a trailing
    ``[0.8]`` / ``% 0.8`` otherwise.
    """

    def __init__(
        self,
        conditions: Sequence[ConditionLike] = (),
        target: Any = None,
        dataspec: Optional[DataSpec] = None,
        ordered: bool = False,
        n_features: Optional[int] = None,
        default_fmt: Optional[str] = None,
        *,
        weight: float,
    ):
        super().__init__(conditions, target=target, dataspec=dataspec, ordered=ordered,
                         n_features=n_features, default_fmt=default_fmt)
        self.weight = float(weight)

    @classmethod
    def from_rule(cls, rule: Rule, weight: float) -> "WeightedRule":
        """A `WeightedRule` copy of `rule` (or `rule` itself with `weight`
        set, if it is already one) -- same body, head, dataspec, order."""
        if isinstance(rule, WeightedRule):
            rule.weight = float(weight)
            return rule
        return cls(
            rule.conditions, target=rule.target, dataspec=rule.dataspec, ordered=rule.ordered,
            n_features=rule.n_features, default_fmt=rule.default_fmt,
            weight=weight,
        )

    def _rebuilt(
        self,
        conditions: Sequence[ConditionLike],
        *,
        dataspec: Optional[DataSpec],
        ordered: bool,
        n_features: Optional[int] = None,
    ) -> "WeightedRule":
        return WeightedRule(
            conditions, target=self.target, dataspec=dataspec, ordered=ordered,
            n_features=n_features, default_fmt=self.default_fmt,
            weight=self.weight,
        )

    def to_string(self, fmt: Optional[str] = None, ascii: bool = False) -> str:
        base = super().to_string(fmt=fmt, ascii=ascii)
        resolved = fmt if fmt is not None else (self.default_fmt or Rule.DEFAULT_FORMAT)
        w = _fmt_weight(self.weight)
        if resolved == "prolog":
            return f"{w}::{base}"
        if resolved == "logic":
            return f"{base}  [{w}]"
        return f"{base}  % {w}"
